spring.application.name=DeliveryRouting

# Configurari Supabase (PostgreSQL) - Inlocuieste cu datele reale din Supabase (Settings -> Database -> Connection string -> JDBC)
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.kthvjwdgpfyovgsmzszt
spring.datasource.password=-_ai%7+HtJCPa4$
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Optimizare Route - URL-ul serviciului Python
python.optimization.service.url=http://localhost:8000/solve
